name: CI-Mac-Win
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  mac-win:
    name: Build/test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      matrix:
        os: [macos-latest,windows-latest]

    steps:

    - uses: actions/checkout@v3

    - uses: haskell-actions/setup@latest

    - name: Build
      run:  cabal build

    - name: Build tests
      run:  cabal build --enable-tests

    - name: Test
      run:  cabal test --enable-tests
